from __future__ import annotations

import argparse
import os
import sys
import tempfile
from pathlib import Path
from typing import Callable

import pyghl as ghl

from .eos_catalog import choose_and_download_eos


def build_parser(prog: str | None = None) -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(prog=prog)
    parser.add_argument(
        "eos_file",
        nargs="?",
        type=Path,
        help="Local EOS HDF5 file. Omit to select and download one from stellarcollapse.org.",
    )
    parser.add_argument("dataset", nargs="?", type=Path)
    parser.add_argument("--checkpoint")
    parser.add_argument("--hdf5_output", type=Path, default=Path("tiny_mlp_model.h5"))
    parser.add_argument("--bundle_output", type=Path, default=Path("tiny_mlp_inference.pt"))
    parser.add_argument("--header_output", type=Path, default=Path("tiny_mlp_weights.h"))
    parser.add_argument("--epochs", type=int, default=2000)
    parser.add_argument("--batch_size", type=int, default=4096)
    parser.add_argument("--patience", type=int, default=250)
    parser.add_argument("--log_path", default="training_log.txt")
    parser.add_argument("--checkpoint_dir", default="checkpoints")
    parser.add_argument("--checkpoint_every", type=int, default=200)
    parser.add_argument("--hidden_dim", type=int, default=3)
    parser.add_argument("--n_hidden", type=int, default=3)
    parser.add_argument("--append_eos", choices=("yes", "no"), default="yes")
    parser.add_argument("--overwrite_eos", action="store_true")
    parser.add_argument("--register_installed_model", choices=("yes", "no"), default="yes")
    parser.add_argument("--overwrite_installed_model", action="store_true")
    parser.add_argument("--force_retrain", action="store_true")
    parser.add_argument("--dataset_n_pts", type=int, default=16)
    parser.add_argument(
        "--target_mode",
        choices=("x_correction", "x_best_correction"),
        default="x_correction",
    )
    parser.add_argument("--scan_points", type=int, default=17)
    return parser


def resolve_eos_file(
    eos_file: Path | None,
    *,
    choose_and_download: Callable[[], Path] = choose_and_download_eos,
) -> Path:
    if eos_file is not None:
        return eos_file
    return choose_and_download()


def main(argv: list[str] | None = None, prog: str | None = None) -> int:
    args = build_parser(prog=prog).parse_args(argv)
    try:
        args.eos_file = resolve_eos_file(args.eos_file)
    except KeyboardInterrupt:
        print("\nEOS table selection cancelled.", file=sys.stderr)
        return 130
    except (OSError, RuntimeError, ValueError) as exc:
        print(f"Error selecting EOS table: {exc}", file=sys.stderr)
        return 1

    from pyghl._nn_hdf5 import (
        append_nn_to_eos_file,
        eos_nn_metadata,
        find_matching_installed_nn_model,
    )

    from .nn_c2p_generate_dataset import generate_dataset

    append_to_eos = args.append_eos == "yes"
    register_installed_model = args.register_installed_model == "yes"
    if not args.force_retrain:
        eos_info = eos_nn_metadata(args.eos_file)
        if eos_info["contains_nn"] and not args.overwrite_eos:
            print(
                f"Skipping training for {args.eos_file}: EOS already contains "
                f"{eos_info['group_name']!r}."
            )
            print("Pass --force_retrain or --overwrite_eos to train again.")
            return 0
        if not eos_info["contains_nn"]:
            installed_model = find_matching_installed_nn_model(args.eos_file)
            if installed_model is not None:
                if append_to_eos:
                    summary = append_nn_to_eos_file(
                        args.eos_file,
                        installed_model,
                        overwrite=args.overwrite_eos,
                        require_eos_match=True,
                    )
                    print(
                        f"Appended matching installed NN model {installed_model} "
                        f"into EOS file: {summary['eos_filename']}."
                    )
                else:
                    print(
                        f"Skipping training for {args.eos_file}: found matching installed NN model "
                        f"{installed_model}."
                    )
                    print("Pass --force_retrain to train again.")
                return 0

    dataset_path = args.dataset
    autogenerated_dataset: Path | None = None
    try:
        if dataset_path is None:
            fd, temp_name = tempfile.mkstemp(
                prefix=f"grhayl_nn_training_{args.eos_file.stem}_",
                suffix=".bin",
            )
            os.close(fd)
            Path(temp_name).unlink(missing_ok=True)
            autogenerated_dataset = Path(temp_name)
            print(f"Generating training dataset for {args.eos_file} ...")
            generate_dataset(
                args.eos_file,
                "train",
                n_pts=args.dataset_n_pts,
                output=autogenerated_dataset,
                target_mode=args.target_mode,
                scan_points=args.scan_points,
            )
            dataset_path = autogenerated_dataset
            print(f"Generated temporary training dataset: {dataset_path}")

        ghl.nn.train_on_dataset(
            dataset_path,
            target_mode=args.target_mode,
            resume_checkpoint=args.checkpoint,
            hdf5_path=args.hdf5_output,
            bundle_path=args.bundle_output,
            header_path=args.header_output,
            eos_path=args.eos_file,
            append_to_eos=append_to_eos,
            overwrite_eos_nn=args.overwrite_eos,
            register_installed_model=register_installed_model,
            overwrite_installed_model=args.overwrite_installed_model,
            force_retrain=args.force_retrain,
            epochs=args.epochs,
            batch_size=args.batch_size,
            patience=args.patience,
            log_path=args.log_path,
            checkpoint_dir=args.checkpoint_dir,
            checkpoint_every=args.checkpoint_every,
            hidden_dim=args.hidden_dim,
            n_hidden=args.n_hidden,
        )
    finally:
        if autogenerated_dataset is not None and autogenerated_dataset.exists():
            autogenerated_dataset.unlink()
            print(f"Removed temporary training dataset: {autogenerated_dataset}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
